Parameters:
  ExecutionRoleArn:
    Type: String
    Description: The SageMaker Studio execution role
  PortfolioName:
    Type: String
    Default: SageMaker Organization Templates
    Description: The name of the portfolio
  PortfolioOwner:
    Type: String
    Default: administrator
    Description: The owner of the portfolio.
  ProductVersion:
    Type: String
    Default: "1.0"
    Description: The product version to deploy
Resources:
  Portfolio856A4190:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      DisplayName:
        Ref: PortfolioName
      ProviderName:
        Ref: PortfolioOwner
      Description: Organization templates for Drift Detection pipeline
  PortfolioPortfolioProductAssociation0d79f0ac3bc7766D6CD6:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId:
        Ref: Portfolio856A4190
      ProductId:
        Ref: Product896941B4
  PortfolioPortolioPrincipalAssociationcc6250f4ae96A7A5C798:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PortfolioId:
        Ref: Portfolio856A4190
      PrincipalARN:
        Ref: ExecutionRoleArn
      PrincipalType: IAM
  Product896941B4:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: Amazon Sagemaker Drift Detection Pipeline
      Owner:
        Ref: PortfolioOwner
      ProvisioningArtifactParameters:
        - DisableTemplateValidation: false
          Info:
            LoadTemplateFromURL: https://amazon-sagemaker-safe-deployment-pipeline.s3.amazonaws.com/drift-pipeline/drift-pipeline-clean.template.json
          Name:
            Ref: ProductVersion
      Description: Amazon SageMaker Project for a build and deployment pipeline that triggers on drift or schedule
      Tags:
        - Key: sagemaker:studio-visibility
          Value: "true"
  ProductsUseRolePolicy7FB0EE21:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":iam::"
                  - Ref: AWS::AccountId
                  - :role/service-role/AmazonSageMakerServiceCatalogProductsUseRole
          - Action:
              - application-autoscaling:DeregisterScalableTarget
              - application-autoscaling:DeleteScalingPolicy
              - application-autoscaling:DescribeScalingPolicies
              - application-autoscaling:PutScalingPolicy
              - application-autoscaling:RegisterScalableTarget
              - application-autoscaling:DescribeScalableTargets
              - iam:CreateServiceLinkedRole
              - cloudwatch:DeleteAlarms
              - cloudwatch:DescribeAlarms
              - cloudwatch:PutMetricAlarm
              - codepipeline:PutJobSuccessResult
              - codepipeline:PutJobFailureResult
            Effect: Allow
            Resource: "*"
          - Action:
              - codepipeline:EnableStageTransition
              - codepipeline:DisableStageTransition
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:codepipeline:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :sagemaker-*
          - Action:
              - events:EnableRule
              - events:DisableRule
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:events:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :rule/sagemaker-*
          - Action: iam:CreateServiceLinkedRole
            Condition:
              StringLike:
                iam:AWSServiceName: sagemaker.application-autoscaling.amazonaws.com
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:iam::"
                  - Ref: AWS::AccountId
                  - :role/aws-service-role/sagemaker.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_SageMakerEndpoint
        Version: "2012-10-17"
      PolicyName: ProductsUseRolePolicy7FB0EE21
      Roles:
        - AmazonSageMakerServiceCatalogProductsUseRole
  LaunchRolePolicyA9E2E5B1:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":s3:::"
                    - "amazon-sagemaker-safe-deployment-pipeline"
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":s3:::"
                    - "amazon-sagemaker-safe-deployment-pipeline"
                    - /*
          - Action:
              - ssm:DescribeParameters
              - ssm:GetParameters
              - ssm:GetParameter
              - ssm:GetParameterHistory
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":ssm:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :parameter
                  - Ref: CodeCommitSeedBucket94EB6088
          - Action:
              - ssm:DescribeParameters
              - ssm:GetParameters
              - ssm:GetParameter
              - ssm:GetParameterHistory
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":ssm:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :parameter
                  - Ref: CodeCommitBuildKey09FC7134
          - Action:
              - ssm:DescribeParameters
              - ssm:GetParameters
              - ssm:GetParameter
              - ssm:GetParameterHistory
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":ssm:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :parameter
                  - Ref: CodeCommitDeployKey5E5A6E47
          - Action:
              - ssm:DescribeParameters
              - ssm:GetParameters
              - ssm:GetParameter
              - ssm:GetParameterHistory
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":ssm:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :parameter
                  - Ref: LambdaKey984A39D9
        Version: "2012-10-17"
      PolicyName: LaunchRolePolicyA9E2E5B1
      Roles:
        - AmazonSageMakerServiceCatalogProductsLaunchRole
  LaunchRoleConstraint:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    Properties:
      PortfolioId:
        Ref: Portfolio856A4190
      ProductId:
        Ref: Product896941B4
      Description:
        Fn::Join:
          - ""
          - - "Launch as arn:"
            - Ref: AWS::Partition
            - ":iam::"
            - Ref: AWS::AccountId
            - :role/service-role/AmazonSageMakerServiceCatalogProductsLaunchRole
      RoleArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":iam::"
            - Ref: AWS::AccountId
            - :role/service-role/AmazonSageMakerServiceCatalogProductsLaunchRole
  CodeCommitSeedBucket94EB6088:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: "amazon-sagemaker-safe-deployment-pipeline"
      Name: /drift-pipeline/CodeCommitSeedBucket
  CodeCommitBuildKey09FC7134:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: "drift-pipeline/build.zip"
      Name: /drift-pipeline/CodeCommitBuildKey
  CodeCommitDeployKey5E5A6E47:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: "drift-pipeline/deploy.zip"
      Name: /drift-pipeline/CodeCommitDeployKey
  LambdaKey984A39D9:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: "drift-pipeline/lambda.zip"
      Name: /drift-pipeline/LambdaKey